
DROP TABLE IF EXISTS HISCORE_SNAPSHOT_SKILL;
DROP TABLE IF EXISTS HISCORE_SNAPSHOT;
DROP TABLE IF EXISTS AR_USER_NAME;
DROP TABLE IF EXISTS RS_USER_NAME;
DROP TABLE IF EXISTS USER_SIGHTING;
DROP TABLE IF EXISTS RS_CLAN_MEMBER;
DROP TABLE IF EXISTS DIR_CLAN_RANK;
DROP TABLE IF EXISTS DIR_ACCOUNT_TYPE;
DROP TABLE IF EXISTS DIR_SKILL;

CREATE TABLE DIR_SKILL (
	SKILL_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	SKILL_NAME VARCHAR(256) NOT NULL,
	DISPLAY_NAME VARCHAR(256) NOT NULL,
	ABBREVIATION VARCHAR(6) NOT NULL,
	LITE_INDEX INTEGER NOT NULL,
	UNIQUE KEY `UNIQUE_SKILL_NAME` (SKILL_NAME),
	UNIQUE KEY `UNIQUE_DISPLAY_NAME` (DISPLAY_NAME)
);

CREATE TABLE DIR_ACCOUNT_TYPE (
	ACCOUNT_TYPE VARCHAR(256) PRIMARY KEY,
	DISPLAY_NAME VARCHAR(256) NOT NULL,
	UNIQUE KEY `UNIQUE_DISPLAY_NAME` (DISPLAY_NAME)
);

CREATE TABLE DIR_CLAN_RANK (
	RANK_NAME VARCHAR(256) PRIMARY KEY,
	DISPLAY_NAME VARCHAR(256) NOT NULL,
	UNIQUE KEY `UNIQUE_DISPLAY_NAME` (DISPLAY_NAME)
);

CREATE TABLE RS_CLAN_MEMBER (
	CLAN_MEMBER_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	RANK_NAME VARCHAR(256) NOT NULL,
	NOTES VARCHAR(2000) DEFAULT NULL,
	FOREIGN KEY (RANK_NAME) REFERENCES DIR_CLAN_RANK(RANK_NAME)
);

CREATE TABLE USER_SIGHTING (
	SIGHTING_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	SIGHTING_TS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	RANK_NAME VARCHAR(256) NOT NULL,
	USER_NAME_ID BIGINT(20) NOT NULL,
	FOREIGN KEY (RANK_NAME) REFERENCES DIR_CLAN_RANK(RANK_NAME)
);

CREATE TABLE RS_USER_NAME (
	USER_NAME_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	CLAN_MEMBER_ID BIGINT(20) DEFAULT NULL,
	USER_NAME VARCHAR(256) NOT NULL,
	FOREIGN KEY (CLAN_MEMBER_ID) REFERENCES RS_CLAN_MEMBER(CLAN_MEMBER_ID),
	UNIQUE KEY `UNIQUE_USERS` (USER_NAME)
);

CREATE TABLE AR_USER_NAME (
	USER_NAME_ID BIGINT(20) PRIMARY KEY,
	CLAN_MEMBER_ID BIGINT(20) NOT NULL,
	USER_NAME VARCHAR(256) NOT NULL,
	FIRST_SEEN_TS TIMESTAMP NOT NULL,
	LAST_SEEN_TS TIMESTAMP NOT NULL,
	FOREIGN KEY (CLAN_MEMBER_ID) REFERENCES RS_CLAN_MEMBER(CLAN_MEMBER_ID)
);

CREATE TABLE HISCORE_SNAPSHOT (
	HISCORE_SNAPSHOT_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	SNAPSHOT_TS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE HISCORE_SNAPSHOT_SKILL (
	HISCORE_SNAPSHOT_ID BIGINT(20) NOT NULL,
	SKILL_ID BIGINT(20) NOT NULL,
	SKILL_LEVEL INTEGER DEFAULT NULL,
	SKILL_EXPERIENCE BIGINT(20) NOT NULL,
	PRIMARY KEY (HISCORE_SNAPSHOT_ID, SKILL_ID),
	FOREIGN KEY (HISCORE_SNAPSHOT_ID) REFERENCES HISCORE_SNAPSHOT(HISCORE_SNAPSHOT_ID)
);

INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('OVERALL', 'Overall', 'TOTAL', 0);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('ATTACK', 'Attack', 'ATK', 1);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('DEFENCE', 'Defence', 'DEF', 2);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('STRENGTH', 'Strength', 'STR', 3);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('HITPOINTS', 'Hitpoints', 'HP', 4);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('RANGED', 'Ranged', 'RNG', 5);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('PRAYER', 'Prayer', 'PRAY', 6);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('MAGIC', 'Magic', 'MAGE', 7);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('COOKING', 'Cooking', 'COOK', 8);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('WOODCUTTING', 'Woodcutting', 'WC', 9);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('FLETCHING', 'Fletching', 'FLETCH', 10);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('FISHING', 'Fishing', 'FISH', 11);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('FIREMAKING', 'Firemaking', 'FM', 12);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('CRAFTING', 'Crafting', 'CRAFT', 13);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('SMITHING', 'Smithing', 'SMITH', 14);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('MINING', 'Mining', 'MINE', 15);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('HERBLORE', 'Herblore', 'HERB', 16);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('AGILITY', 'Agility', 'AGIL', 17);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('THIEVING', 'Thieving', 'THIEV', 18);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('SLAYER', 'Slayer', 'SLAY', 19);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('FARMING', 'Farming', 'FARM', 20);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('RUNECRAFT', 'Runecraft', 'RC', 21);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('HUNTER', 'Hunter', 'HUNT', 22);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('CONSTRUCTION', 'Construction', 'CONS', 23);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('CLUE_EASY', 'Clue Scrolls (easy)', 'CE', 24);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('CLUE_MED', 'Clue Scrolls (medium)', 'CM', 25);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('CLUE_ALL', 'Clue Scrolls (all)', 'CA', 26);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('BOUNTY_ROGUE', 'Bounty Hunter - Rogue', 'BR', 27);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('BOUNTY_HUNTER', 'Bounty Hunter - Hunter', 'BH', 28);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('CLUE_HARD', 'Clue Scrolls (hard)', 'CH', 29);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('LMS', 'LMS - Rank', 'LMS', 30);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('CLUE_ELITE', 'Clue Scrolls (elite)', 'CEL', 31);
INSERT INTO DIR_SKILL (SKILL_NAME, DISPLAY_NAME, ABBREVIATION, LITE_INDEX) VALUES ('CLUE_MASTER', 'Clue Scrolls (master)', 'CMA', 32);

INSERT INTO DIR_ACCOUNT_TYPE (ACCOUNT_TYPE, DISPLAY_NAME) VALUES ('REGULAR', 'Regular');
INSERT INTO DIR_ACCOUNT_TYPE (ACCOUNT_TYPE, DISPLAY_NAME) VALUES ('IRONMAN', 'Ironman');
INSERT INTO DIR_ACCOUNT_TYPE (ACCOUNT_TYPE, DISPLAY_NAME) VALUES ('HARDCORE', 'Hardcore Ironman');
INSERT INTO DIR_ACCOUNT_TYPE (ACCOUNT_TYPE, DISPLAY_NAME) VALUES ('ULTIMATE', 'Ultimate Ironman');

INSERT INTO DIR_CLAN_RANK (RANK_NAME, DISPLAY_NAME) VALUES ('CHANNEL_OWNER', 'Channel owner');
INSERT INTO DIR_CLAN_RANK (RANK_NAME, DISPLAY_NAME) VALUES ('GENERAL', 'General');
INSERT INTO DIR_CLAN_RANK (RANK_NAME, DISPLAY_NAME) VALUES ('CAPTAIN', 'Captain');
INSERT INTO DIR_CLAN_RANK (RANK_NAME, DISPLAY_NAME) VALUES ('LIEUTENANT', 'Lieutenant');
INSERT INTO DIR_CLAN_RANK (RANK_NAME, DISPLAY_NAME) VALUES ('SERGEANT', 'Sergeant');
INSERT INTO DIR_CLAN_RANK (RANK_NAME, DISPLAY_NAME) VALUES ('CORPORAL', 'Corporal');
INSERT INTO DIR_CLAN_RANK (RANK_NAME, DISPLAY_NAME) VALUES ('RECRUIT', 'Recruit');
INSERT INTO DIR_CLAN_RANK (RANK_NAME, DISPLAY_NAME) VALUES ('FRIEND', 'Friend');
INSERT INTO DIR_CLAN_RANK (RANK_NAME, DISPLAY_NAME) VALUES ('UNRANKED', 'Unranked');
INSERT INTO DIR_CLAN_RANK (RANK_NAME, DISPLAY_NAME) VALUES ('UNKNOWN', 'Unknown');
